<template>
  <div class="space-y-4 p-6 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl min-h-screen">
    <h1 class="text-3xl font-bold mb-4 text-gray-900 dark:text-gray-100">
      BoxIcons ({{ filteredIcons.length }})
    </h1>

    <input
      v-model="searchQuery"
      type="text"
      placeholder="Search icons..."
      class="mb-6 p-2 rounded-2xl w-full dark:bg-gray-800 dark:text-gray-100"
    />

    <div class="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-4 gap-4">
      <div
        v-for="icon in paginatedIcons"
        :key="icon.name"
        @click="copyIcon(icon.name)"
        class="flex flex-col items-center p-3 rounded hover:bg-gray-100 dark:hover:bg-gray-800 transition cursor-pointer"
      >
        <i :class="'bx ' + icon.class"></i>
        <span class="mt-2 text-xs text-gray-600 dark:text-gray-400 text-center">
          {{ icon.name }}
        </span>
        <span
          v-if="copiedIcon === icon.name"
          class="text-sky-400 text-xs mt-1 animate-pulse"
        >
          Copied!
        </span>
      </div>
    </div>

    <Pagination 
      v-model:page="page" 
      :pages="totalPages" 
      class="mt-6"
    />
  </div>
</template>

<script setup>
import { ref, computed, watchEffect } from 'vue'
import Pagination from '../components/Pagination.vue'

// Complete BoxIcons data
const boxIcons = [
  { name: 'home', class: 'bx-home' },
  { name: 'user', class: 'bx-user' },
  { name: 'search', class: 'bx-search' },
  { name: 'heart', class: 'bx-heart' },
  { name: 'cart', class: 'bx-cart' },
  { name: 'bell', class: 'bx-bell' },
  { name: 'menu', class: 'bx-menu' },
  { name: 'x', class: 'bx-x' },
  { name: 'plus', class: 'bx-plus' },
  { name: 'minus', class: 'bx-minus' },
  { name: 'chevron-up', class: 'bx-chevron-up' },
  { name: 'chevron-down', class: 'bx-chevron-down' },
  { name: 'chevron-left', class: 'bx-chevron-left' },
  { name: 'chevron-right', class: 'bx-chevron-right' },
  { name: 'arrow-back', class: 'bx-arrow-back' },
  { name: 'arrow-forward', class: 'bx-arrow-forward' },
  { name: 'download', class: 'bx-download' },
  { name: 'upload', class: 'bx-upload' },
  { name: 'trash', class: 'bx-trash' },
  { name: 'edit', class: 'bx-edit' },
  { name: 'cog', class: 'bx-cog' },
  { name: 'wrench', class: 'bx-wrench' },
  { name: 'info-circle', class: 'bx-info-circle' },
  { name: 'question-mark', class: 'bx-question-mark' },
  { name: 'check', class: 'bx-check' },
  { name: 'x-circle', class: 'bx-x-circle' },
  { name: 'check-circle', class: 'bx-check-circle' },
  { name: 'star', class: 'bx-star' },
  { name: 'bookmark', class: 'bx-bookmark' },
  { name: 'calendar', class: 'bx-calendar' },
  { name: 'time', class: 'bx-time' },
  { name: 'folder', class: 'bx-folder' },
  { name: 'file', class: 'bx-file' },
  { name: 'image', class: 'bx-image' },
  { name: 'camera', class: 'bx-camera' },
  { name: 'video', class: 'bx-video' },
  { name: 'microphone', class: 'bx-microphone' },
  { name: 'phone', class: 'bx-phone' },
  { name: 'envelope', class: 'bx-envelope' },
  { name: 'location', class: 'bx-location' },
  { name: 'map', class: 'bx-map' },
  { name: 'navigation', class: 'bx-navigation' },
  { name: 'compass', class: 'bx-compass' },
  { name: 'grid', class: 'bx-grid' },
  { name: 'list', class: 'bx-list' },
  { name: 'grid-alt', class: 'bx-grid-alt' },
  { name: 'data', class: 'bx-data' },
  { name: 'chart', class: 'bx-chart' },
  { name: 'pie-chart', class: 'bx-pie-chart' },
  { name: 'bar-chart', class: 'bx-bar-chart' },
  { name: 'line-chart', class: 'bx-line-chart' },
  { name: 'area-chart', class: 'bx-area-chart' },
  { name: 'purchase-tag', class: 'bx-purchase-tag' },
  { name: 'tag', class: 'bx-tag' },
  { name: 'credit-card', class: 'bx-credit-card' },
  { name: 'dollar', class: 'bx-dollar' },
  { name: 'euro', class: 'bx-euro' },
  { name: 'pound', class: 'bx-pound' },
  { name: 'yen', class: 'bx-yen' },
  { name: 'bitcoin', class: 'bx-bitcoin' },
  { name: 'lock', class: 'bx-lock' },
  { name: 'unlock', class: 'bx-unlock' },
  { name: 'shield', class: 'bx-shield' },
  { name: 'key', class: 'bx-key' },
  { name: 'wifi', class: 'bx-wifi' },
  { name: 'wifi-off', class: 'bx-wifi-off' },
  { name: 'bluetooth', class: 'bx-bluetooth' },
  { name: 'network-chart', class: 'bx-network-chart' },
  { name: 'cloud', class: 'bx-cloud' },
  { name: 'cloud-upload', class: 'bx-cloud-upload' },
  { name: 'cloud-download', class: 'bx-cloud-download' },
  { name: 'cloud-lightning', class: 'bx-cloud-lightning' },
  { name: 'cloud-rain', class: 'bx-cloud-rain' },
  { name: 'cloud-snow', class: 'bx-cloud-snow' },
  { name: 'sun', class: 'bx-sun' },
  { name: 'moon', class: 'bx-moon' },
  { name: 'wind', class: 'bx-wind' },
  { name: 'droplet', class: 'bx-droplet' },
  { name: 'color-fill', class: 'bx-color-fill' },
  { name: 'palette', class: 'bx-palette' },
  { name: 'brush', class: 'bx-brush' },
  { name: 'highlight', class: 'bx-highlight' },
  { name: 'eraser', class: 'bx-eraser' },
  { name: 'text', class: 'bx-text' },
  { name: 'bold', class: 'bx-bold' },
  { name: 'italic', class: 'bx-italic' },
  { name: 'underline', class: 'bx-underline' },
  { name: 'strikethrough', class: 'bx-strikethrough' },
  { name: 'font', class: 'bx-font' },
  { name: 'font-color', class: 'bx-font-color' },
  { name: 'font-size', class: 'bx-font-size' },
  { name: 'align-left', class: 'bx-align-left' },
  { name: 'align-center', class: 'bx-align-center' },
  { name: 'align-right', class: 'bx-align-right' },
  { name: 'align-justify', class: 'bx-align-justify' },
  { name: 'list-plus', class: 'bx-list-plus' },
  { name: 'list-minus', class: 'bx-list-minus' },
  { name: 'list-check', class: 'bx-list-check' },
  { name: 'list-ul', class: 'bx-list-ul' },
  { name: 'list-ol', class: 'bx-list-ol' },
  { name: 'indent', class: 'bx-indent' },
  { name: 'outdent', class: 'bx-outdent' },
  { name: 'link', class: 'bx-link' },
  { name: 'unlink', class: 'bx-unlink' },
  { name: 'paperclip', class: 'bx-paperclip' },
  { name: 'attachment', class: 'bx-attachment' },
  { name: 'cut', class: 'bx-cut' },
  { name: 'copy', class: 'bx-copy' },
  { name: 'paste', class: 'bx-paste' },
  { name: 'save', class: 'bx-save' },
  { name: 'undo', class: 'bx-undo' },
  { name: 'redo', class: 'bx-redo' },
  { name: 'zoom-in', class: 'bx-zoom-in' },
  { name: 'zoom-out', class: 'bx-zoom-out' },
  { name: 'search-alt', class: 'bx-search-alt' },
  { name: 'expand', class: 'bx-expand' },
  { name: 'collapse', class: 'bx-collapse' },
  { name: 'fullscreen', class: 'bx-fullscreen' },
  { name: 'exit-fullscreen', class: 'bx-exit-fullscreen' },
  { name: 'refresh', class: 'bx-refresh' },
  { name: 'repost', class: 'bx-repost' },
  { name: 'share', class: 'bx-share' },
  { name: 'share-alt', class: 'bx-share-alt' },
  { name: 'send', class: 'bx-send' },
  { name: 'comment', class: 'bx-comment' },
  { name: 'chat', class: 'bx-chat' },
  { name: 'message', class: 'bx-message' },
  { name: 'message-alt', class: 'bx-message-alt' },
  { name: 'message-rounded', class: 'bx-message-rounded' },
  { name: 'message-square', class: 'bx-message-square' },
  { name: 'message-dots', class: 'bx-message-dots' },
  { name: 'notification', class: 'bx-notification' },
  { name: 'notification-off', class: 'bx-notification-off' },
  { name: 'group', class: 'bx-group' },
  { name: 'user-plus', class: 'bx-user-plus' },
  { name: 'user-minus', class: 'bx-user-minus' },
  { name: 'user-x', class: 'bx-user-x' },
  { name: 'user-check', class: 'bx-user-check' },
  { name: 'user-voice', class: 'bx-user-voice' },
  { name: 'user-pin', class: 'bx-user-pin' },
  { name: 'happy', class: 'bx-happy' },
  { name: 'smile', class: 'bx-smile' },
  { name: 'laugh', class: 'bx-laugh' },
  { name: 'sad', class: 'bx-sad' },
  { name: 'confused', class: 'bx-confused' },
  { name: 'angry', class: 'bx-angry' },
  { name: 'cool', class: 'bx-cool' },
  { name: 'tired', class: 'bx-tired' },
  { name: 'wink', class: 'bx-wink' },
  { name: 'wink-smile', class: 'bx-wink-smile' },
  { name: 'meh', class: 'bx-meh' },
  { name: 'meh-blank', class: 'bx-meh-blank' },
  { name: 'frown', class: 'bx-frown' },
  { name: 'ghost', class: 'bx-ghost' },
  { name: 'angry', class: 'bx-angry' },
  { name: 'shocked', class: 'bx-shocked' },
  { name: 'sick', class: 'bx-sick' },
  { name: 'sleepy', class: 'bx-sleepy' },
  { name: 'dizzy', class: 'bx-dizzy' },
  { name: 'plus-medical', class: 'bx-plus-medical' },
  { name: 'first-aid', class: 'bx-first-aid' },
  { name: 'injection', class: 'bx-injection' },
  { name: 'thermometer', class: 'bx-thermometer' },
  { name: 'pulse', class: 'bx-pulse' },
  { name: 'heart-circle', class: 'bx-heart-circle' },
  { name: 'heart-square', class: 'bx-heart-square' },
  { name: 'heart-pulse', class: 'bx-heart-pulse' },
  { name: 'abacus', class: 'bx-abacus' },
  { name: 'atom', class: 'bx-atom' },
  { name: 'award', class: 'bx-award' },
  { name: 'badge', class: 'bx-badge' },
  { name: 'band-aid', class: 'bx-band-aid' },
  { name: 'barcode', class: 'bx-barcode' },
  { name: 'basketball', class: 'bx-basketball' },
  { name: 'bath', class: 'bx-bath' },
  { name: 'battery', class: 'bx-battery' },
  { name: 'bed', class: 'bx-bed' },
  { name: 'beer', class: 'bx-beer' },
  { name: 'bell-plus', class: 'bx-bell-plus' },
  { name: 'bell-minus', class: 'bx-bell-minus' },
  { name: 'bell-off', class: 'bx-bell-off' },
  { name: 'bible', class: 'bx-bible' },
  { name: 'bone', class: 'bx-bone' },
  { name: 'book', class: 'bx-book' },
  { name: 'book-open', class: 'bx-book-open' },
  { name: 'bookmark-plus', class: 'bx-bookmark-plus' },
  { name: 'bookmark-minus', class: 'bx-bookmark-minus' },
  { name: 'bowling-ball', class: 'bx-bowling-ball' },
  { name: 'box', class: 'bx-box' },
  { name: 'briefcase', class: 'bx-briefcase' },
  { name: 'bug', class: 'bx-bug' },
  { name: 'building', class: 'bx-building' },
  { name: 'bulb', class: 'bx-bulb' },
  { name: 'bus', class: 'bx-bus' },
  { name: 'cake', class: 'bx-cake' },
  { name: 'calculator', class: 'bx-calculator' },
  { name: 'calendar-alt', class: 'bx-calendar-alt' },
  { name: 'calendar-check', class: 'bx-calendar-check' },
  { name: 'calendar-edit', class: 'bx-calendar-edit' },
  { name: 'calendar-event', class: 'bx-calendar-event' },
  { name: 'calendar-minus', class: 'bx-calendar-minus' },
  { name: 'calendar-plus', class: 'bx-calendar-plus' },
  { name: 'calendar-x', class: 'bx-calendar-x' },
  { name: 'camera-home', class: 'bx-camera-home' },
  { name: 'camera-movie', class: 'bx-camera-movie' },
  { name: 'camera-off', class: 'bx-camera-off' },
  { name: 'car', class: 'bx-car' },
  { name: 'cart-alt', class: 'bx-cart-alt' },
  { name: 'cast', class: 'bx-cast' },
  { name: 'category', class: 'bx-category' },
  { name: 'certification', class: 'bx-certification' },
  { name: 'chair', class: 'bx-chair' },
  { name: 'chalkboard', class: 'bx-chalkboard' },
  { name: 'chart', class: 'bx-chart' },
  { name: 'chip', class: 'bx-chip' },
  { name: 'church', class: 'bx-church' },
  { name: 'coffee', class: 'bx-coffee' },
  { name: 'coffee-togo', class: 'bx-coffee-togo' },
  { name: 'cog', class: 'bx-cog' },
  { name: 'collection', class: 'bx-collection' },
  { name: 'compass', class: 'bx-compass' },
  { name: 'component', class: 'bx-component' },
  { name: 'confused', class: 'bx-confused' },
  { name: 'conversation', class: 'bx-conversation' },
  { name: 'cookie', class: 'bx-cookie' },
  { name: 'cool', class: 'bx-cool' },
  { name: 'copy-alt', class: 'bx-copy-alt' },
  { name: 'copyright', class: 'bx-copyright' },
  { name: 'credit-card-alt', class: 'bx-credit-card-alt' },
  { name: 'crop', class: 'bx-crop' },
  { name: 'crown', class: 'bx-crown' },
  { name: 'cube', class: 'bx-cube' },
  { name: 'cube-alt', class: 'bx-cube-alt' },
  { name: 'cuboid', class: 'bx-cuboid' },
  { name: 'cylinder', class: 'bx-cylinder' },
  { name: 'dashboard', class: 'bx-dashboard' },
  { name: 'data', class: 'bx-data' },
  { name: 'desktop', class: 'bx-desktop' },
  { name: 'dialpad', class: 'bx-dialpad' },
  { name: 'diamond', class: 'bx-diamond' },
  { name: 'dice', class: 'bx-dice' },
  { name: 'dice-1', class: 'bx-dice-1' },
  { name: 'dice-2', class: 'bx-dice-2' },
  { name: 'dice-3', class: 'bx-dice-3' },
  { name: 'dice-4', class: 'bx-dice-4' },
  { name: 'dice-5', class: 'bx-dice-5' },
  { name: 'dice-6', class: 'bx-dice-6' },
  { name: 'directions', class: 'bx-directions' },
  { name: 'disc', class: 'bx-disc' },
  { name: 'dish', class: 'bx-dish' },
  { name: 'doctor', class: 'bx-doctor' },
  { name: 'dog', class: 'bx-dog' },
  { name: 'dollar-circle', class: 'bx-dollar-circle' },
  { name: 'donate-blood', class: 'bx-donate-blood' },
  { name: 'donate-heart', class: 'bx-donate-heart' },
  { name: 'door-open', class: 'bx-door-open' },
  { name: 'doughnut-chart', class: 'bx-doughnut-chart' },
  { name: 'drink', class: 'bx-drink' },
  { name: 'droplet', class: 'bx-droplet' },
  { name: 'dumbbell', class: 'bx-dumbbell' },
  { name: 'duplicate', class: 'bx-duplicate' },
  { name: 'edit-alt', class: 'bx-edit-alt' },
  { name: 'envelope-open', class: 'bx-envelope-open' },
  { name: 'eraser', class: 'bx-eraser' },
  { name: 'error', class: 'bx-error' },
  { name: 'error-alt', class: 'bx-error-alt' },
  { name: 'error-circle', class: 'bx-error-circle' },
  { name: 'exit', class: 'bx-exit' },
  { name: 'extension', class: 'bx-extension' },
  { name: 'face', class: 'bx-face' },
  { name: 'factory', class: 'bx-factory' },
  { name: 'fast-forward', class: 'bx-fast-forward' },
  { name: 'file-blank', class: 'bx-file-blank' },
  { name: 'file-find', class: 'bx-file-find' },
  { name: 'film', class: 'bx-film' },
  { name: 'filter', class: 'bx-filter' },
  { name: 'filter-alt', class: 'bx-filter-alt' },
  { name: 'fingerprint', class: 'bx-fingerprint' },
  { name: 'first-page', class: 'bx-first-page' },
  { name: 'flag', class: 'bx-flag' },
  { name: 'folder-open', class: 'bx-folder-open' },
  { name: 'food-menu', class: 'bx-food-menu' },
  { name: 'fridge', class: 'bx-fridge' },
  { name: 'game', class: 'bx-game' },
  { name: 'gas-pump', class: 'bx-gas-pump' },
  { name: 'ghost', class: 'bx-ghost' },
  { name: 'gift', class: 'bx-gift' },
  { name: 'graduation', class: 'bx-graduation' },
  { name: 'grid', class: 'bx-grid' },
  { name: 'grid-alt', class: 'bx-grid-alt' },
  { name: 'group', class: 'bx-group' },
  { name: 'handicap', class: 'bx-handicap' },
  { name: 'happy', class: 'bx-happy' },
  { name: 'happy-alt', class: 'bx-happy-alt' },
  { name: 'happy-beaming', class: 'bx-happy-beaming' },
  { name: 'happy-heart-eyes', class: 'bx-happy-heart-eyes' },
  { name: 'hash', class: 'bx-hash' },
  { name: 'hdd', class: 'bx-hdd' },
  { name: 'heading', class: 'bx-heading' },
  { name: 'headphone', class: 'bx-headphone' },
  { name: 'health', class: 'bx-health' },
  { name: 'heart', class: 'bx-heart' },
  { name: 'heart-circle', class: 'bx-heart-circle' },
  { name: 'heart-square', class: 'bx-heart-square' },
  { name: 'help-circle', class: 'bx-help-circle' },
  { name: 'hide', class: 'bx-hide' },
  { name: 'highlight', class: 'bx-highlight' },
  { name: 'history', class: 'bx-history' },
  { name: 'hive', class: 'bx-hive' },
  { name: 'home', class: 'bx-home' },
  { name: 'home-alt', class: 'bx-home-alt' },
  { name: 'home-circle', class: 'bx-home-circle' },
  { name: 'home-heart', class: 'bx-home-heart' },
  { name: 'home-smile', class: 'bx-home-smile' },
  { name: 'hot', class: 'bx-hot' },
  { name: 'hotel', class: 'bx-hotel' },
  { name: 'hourglass', class: 'bx-hourglass' },
  { name: 'id-card', class: 'bx-id-card' },
  { name: 'image', class: 'bx-image' },
  { name: 'image-add', class: 'bx-image-add' },
  { name: 'image-alt', class: 'bx-image-alt' },
  { name: 'inbox', class: 'bx-inbox' },
  { name: 'info-circle', class: 'bx-info-circle' },
  { name: 'institution', class: 'bx-institution' },
  { name: 'joystick', class: 'bx-joystick' },
  { name: 'joystick-alt', class: 'bx-joystick-alt' },
  { name: 'key', class: 'bx-key' },
  { name: 'keyboard', class: 'bx-keyboard' },
  { name: 'label', class: 'bx-label' },
  { name: 'landscape', class: 'bx-landscape' },
  { name: 'laptop', class: 'bx-laptop' },
  { name: 'last-page', class: 'bx-last-page' },
  { name: 'laugh', class: 'bx-laugh' },
  { name: 'layer', class: 'bx-layer' },
  { name: 'layer-plus', class: 'bx-layer-plus' },
  { name: 'layout', class: 'bx-layout' },
  { name: 'leaf', class: 'bx-leaf' },
  { name: 'left-arrow', class: 'bx-left-arrow' },
  { name: 'left-arrow-alt', class: 'bx-left-arrow-alt' },
  { name: 'left-arrow-circle', class: 'bx-left-arrow-circle' },
  { name: 'left-down-arrow-circle', class: 'bx-left-down-arrow-circle' },
  { name: 'left-indent', class: 'bx-left-indent' },
  { name: 'left-top-arrow-circle', class: 'bx-left-top-arrow-circle' },
  { name: 'like', class: 'bx-like' },
  { name: 'line-chart', class: 'bx-line-chart' },
  { name: 'link', class: 'bx-link' },
  { name: 'link-alt', class: 'bx-link-alt' },
  { name: 'link-external', class: 'bx-link-external' },
  { name: 'lira', class: 'bx-lira' },
  { name: 'list-check', class: 'bx-list-check' },
  { name: 'list-minus', class: 'bx-list-minus' },
  { name: 'list-ol', class: 'bx-list-ol' },
  { name: 'list-plus', class: 'bx-list-plus' },
  { name: 'list-ul', class: 'bx-list-ul' },
  { name: 'loader', class: 'bx-loader' },
  { name: 'loader-alt', class: 'bx-loader-alt' },
  { name: 'loader-circle', class: 'bx-loader-circle' },
  { name: 'location-plus', class: 'bx-location-plus' },
  { name: 'lock', class: 'bx-lock' },
  { name: 'lock-alt', class: 'bx-lock-alt' },
  { name: 'lock-open', class: 'bx-lock-open' },
  { name: 'lock-open-alt', class: 'bx-lock-open-alt' },
  { name: 'log-in', class: 'bx-log-in' },
  { name: 'log-out', class: 'bx-log-out' },
  { name: 'low-vision', class: 'bx-low-vision' },
  { name: 'magic-wand', class: 'bx-magic-wand' },
  { name: 'magnet', class: 'bx-magnet' },
  { name: 'map', class: 'bx-map' },
  { name: 'map-alt', class: 'bx-map-alt' },
  { name: 'map-pin', class: 'bx-map-pin' },
  { name: 'mask', class: 'bx-mask' },
  { name: 'medal', class: 'bx-medal' },
  { name: 'megaphone', class: 'bx-megaphone' },
  { name: 'meh', class: 'bx-meh' },
  { name: 'meh-alt', class: 'bx-meh-alt' },
  { name: 'meh-blank', class: 'bx-meh-blank' },
  { name: 'memory-card', class: 'bx-memory-card' },
  { name: 'menu', class: 'bx-menu' },
  { name: 'menu-alt-left', class: 'bx-menu-alt-left' },
  { name: 'menu-alt-right', class: 'bx-menu-alt-right' },
  { name: 'merge', class: 'bx-merge' },
  { name: 'message', class: 'bx-message' },
  { name: 'message-alt', class: 'bx-message-alt' },
  { name: 'message-alt-dots', class: 'bx-message-alt-dots' },
  { name: 'message-dots', class: 'bx-message-dots' },
  { name: 'message-rounded', class: 'bx-message-rounded' },
  { name: 'message-square', class: 'bx-message-square' },
  { name: 'microphone', class: 'bx-microphone' },
  { name: 'microphone-off', class: 'bx-microphone-off' },
  { name: 'minus', class: 'bx-minus' },
  { name: 'minus-circle', class: 'bx-minus-circle' },
  { name: 'mobile', class: 'bx-mobile' },
  { name: 'mobile-alt', class: 'bx-mobile-alt' },
  { name: 'mobile-landscape', class: 'bx-mobile-landscape' },
  { name: 'mobile-vibration', class: 'bx-mobile-vibration' },
  { name: 'money', class: 'bx-money' },
  { name: 'moon', class: 'bx-moon' },
  { name: 'mouse', class: 'bx-mouse' },
  { name: 'mouse-alt', class: 'bx-mouse-alt' },
  { name: 'move', class: 'bx-move' },
  { name: 'move-horizontal', class: 'bx-move-horizontal' },
  { name: 'move-vertical', class: 'bx-move-vertical' },
  { name: 'movie', class: 'bx-movie' },
  { name: 'music', class: 'bx-music' },
  { name: 'navigation', class: 'bx-navigation' },
  { name: 'network-chart', class: 'bx-network-chart' },
  { name: 'news', class: 'bx-news' },
  { name: 'no-entry', class: 'bx-no-entry' },
  { name: 'note', class: 'bx-note' },
  { name: 'notepad', class: 'bx-notepad' },
  { name: 'notification', class: 'bx-notification' },
  { name: 'notification-off', class: 'bx-notification-off' },
  { name: 'package', class: 'bx-package' },
  { name: 'paint', class: 'bx-paint' },
  { name: 'paint-roll', class: 'bx-paint-roll' },
  { name: 'palette', class: 'bx-palette' },
  { name: 'paper-plane', class: 'bx-paper-plane' },
  { name: 'paragraph', class: 'bx-paragraph' },
  { name: 'party', class: 'bx-party' },
  { name: 'paste', class: 'bx-paste' },
  { name: 'pause', class: 'bx-pause' },
  { name: 'pause-circle', class: 'bx-pause-circle' },
  { name: 'pen', class: 'bx-pen' },
  { name: 'pencil', class: 'bx-pencil' },
  { name: 'phone', class: 'bx-phone' },
  { name: 'phone-call', class: 'bx-phone-call' },
  { name: 'phone-incoming', class: 'bx-phone-incoming' },
  { name: 'phone-outgoing', class: 'bx-phone-outgoing' },
  { name: 'photo-album', class: 'bx-photo-album' },
  { name: 'pie-chart', class: 'bx-pie-chart' },
  { name: 'pie-chart-alt', class: 'bx-pie-chart-alt' },
  { name: 'pin', class: 'bx-pin' },
  { name: 'plane', class: 'bx-plane' },
  { name: 'plane-alt', class: 'bx-plane-alt' },
  { name: 'planet', class: 'bx-planet' },
  { name: 'play', class: 'bx-play' },
  { name: 'play-circle', class: 'bx-play-circle' },
  { name: 'plug', class: 'bx-plug' },
  { name: 'plus', class: 'bx-plus' },
  { name: 'plus-circle', class: 'bx-plus-circle' },
  { name: 'plus-medical', class: 'bx-plus-medical' },
  { name: 'podcast', class: 'bx-podcast' },
  { name: 'pointer', class: 'bx-pointer' },
  { name: 'poll', class: 'bx-poll' },
  { name: 'polygon', class: 'bx-polygon' },
  { name: 'printer', class: 'bx-printer' },
  { name: 'purchase-tag', class: 'bx-purchase-tag' },
  { name: 'purchase-tag-alt', class: 'bx-purchase-tag-alt' },
  { name: 'pyramid', class: 'bx-pyramid' },
  { name: 'quote', class: 'bx-quote' },
  { name: 'quote-alt-left', class: 'bx-quote-alt-left' },
  { name: 'quote-alt-right', class: 'bx-quote-alt-right' },
  { name: 'radar', class: 'bx-radar' },
  { name: 'radio', class: 'bx-radio' },
  { name: 'receipt', class: 'bx-receipt' },
  { name: 'rectangle', class: 'bx-rectangle' },
  { name: 'recycle', class: 'bx-recycle' },
  { name: 'redo', class: 'bx-redo' },
  { name: 'rename', class: 'bx-rename' },
  { name: 'repeat', class: 'bx-repeat' },
  { name: 'reply', class: 'bx-reply' },
  { name: 'reply-all', class: 'bx-reply-all' },
  { name: 'reset', class: 'bx-reset' },
  { name: 'restaurant', class: 'bx-restaurant' },
  { name: 'rewind', class: 'bx-rewind' },
  { name: 'rewind-circle', class: 'bx-rewind-circle' },
  { name: 'right-arrow', class: 'bx-right-arrow' },
  { name: 'right-arrow-alt', class: 'bx-right-arrow-alt' },
  { name: 'right-arrow-circle', class: 'bx-right-arrow-circle' },
  { name: 'right-down-arrow-circle', class: 'bx-right-down-arrow-circle' },
  { name: 'right-indent', class: 'bx-right-indent' },
  { name: 'right-top-arrow-circle', class: 'bx-right-top-arrow-circle' },
  { name: 'rocket', class: 'bx-rocket' },
  { name: 'rotate-left', class: 'bx-rotate-left' },
  { name: 'rotate-right', class: 'bx-rotate-right' },
  { name: 'rss', class: 'bx-rss' },
  { name: 'ruler', class: 'bx-ruler' },
  { name: 'run', class: 'bx-run' },
  { name: 'sad', class: 'bx-sad' },
  { name: 'save', class: 'bx-save' },
  { name: 'scan', class: 'bx-scan' },
  { name: 'screenshot', class: 'bx-screenshot' },
  { name: 'search', class: 'bx-search' },
  { name: 'search-alt', class: 'bx-search-alt' },
  { name: 'search-alt-2', class: 'bx-search-alt-2' },
  { name: 'selection', class: 'bx-selection' },
  { name: 'select-multiple', class: 'bx-select-multiple' },
  { name: 'send', class: 'bx-send' },
  { name: 'server', class: 'bx-server' },
  { name: 'shape-circle', class: 'bx-shape-circle' },
  { name: 'shape-polygon', class: 'bx-shape-polygon' },
  { name: 'shape-square', class: 'bx-shape-square' },
  { name: 'shape-triangle', class: 'bx-shape-triangle' },
  { name: 'share', class: 'bx-share' },
  { name: 'share-alt', class: 'bx-share-alt' },
  { name: 'shield', class: 'bx-shield' },
  { name: 'shield-alt', class: 'bx-shield-alt' },
  { name: 'shield-quarter', class: 'bx-shield-quarter' },
  { name: 'ship', class: 'bx-ship' },
  { name: 'shocked', class: 'bx-shocked' },
  { name: 'shopping-bag', class: 'bx-shopping-bag' },
  { name: 'show', class: 'bx-show' },
  { name: 'skip-next', class: 'bx-skip-next' },
  { name: 'skip-previous', class: 'bx-skip-previous' },
  { name: 'sleepy', class: 'bx-sleepy' },
  { name: 'slideshow', class: 'bx-slideshow' },
  { name: 'smile', class: 'bx-smile' },
  { name: 'sort', class: 'bx-sort' },
  { name: 'sort-a-z', class: 'bx-sort-a-z' },
  { name: 'sort-z-a', class: 'bx-sort-z-a' },
  { name: 'spa', class: 'bx-spa' },
  { name: 'speaker', class: 'bx-speaker' },
  { name: 'spray-can', class: 'bx-spray-can' },
  { name: 'spreadsheet', class: 'bx-spreadsheet' },
  { name: 'square', class: 'bx-square' },
  { name: 'square-rounded', class: 'bx-square-rounded' },
  { name: 'star', class: 'bx-star' },
  { name: 'station', class: 'bx-station' },
  { name: 'stats', class: 'bx-stats' },
  { name: 'sticker', class: 'bx-sticker' },
  { name: 'stop', class: 'bx-stop' },
  { name: 'stop-circle', class: 'bx-stop-circle' },
  { name: 'stopwatch', class: 'bx-stopwatch' },
  { name: 'store', class: 'bx-store' },
  { name: 'street-view', class: 'bx-street-view' },
  { name: 'strikethrough', class: 'bx-strikethrough' },
  { name: 'subdirectory-left', class: 'bx-subdirectory-left' },
  { name: 'subdirectory-right', class: 'bx-subdirectory-right' },
  { name: 'sun', class: 'bx-sun' },
  { name: 'support', class: 'bx-support' },
  { name: 'swim', class: 'bx-swim' },
  { name: 'sync', class: 'bx-sync' },
  { name: 'tab', class: 'bx-tab' },
  { name: 'table', class: 'bx-table' },
  { name: 'tachometer', class: 'bx-tachometer' },
  { name: 'tag', class: 'bx-tag' },
  { name: 'target-lock', class: 'bx-target-lock' },
  { name: 'task', class: 'bx-task' },
  { name: 'taxi', class: 'bx-taxi' },
  { name: 'tennis-ball', class: 'bx-tennis-ball' },
  { name: 'terminal', class: 'bx-terminal' },
  { name: 'test-tube', class: 'bx-test-tube' },
  { name: 'text', class: 'bx-text' },
  { name: 'time', class: 'bx-time' },
  { name: 'time-five', class: 'bx-time-five' },
  { name: 'timer', class: 'bx-timer' },
  { name: 'tired', class: 'bx-tired' },
  { name: 'toggle-left', class: 'bx-toggle-left' },
  { name: 'toggle-right', class: 'bx-toggle-right' },
  { name: 'tone', class: 'bx-tone' },
  { name: 'traffic', class: 'bx-traffic' },
  { name: 'train', class: 'bx-train' },
  { name: 'transfer', class: 'bx-transfer' },
  { name: 'transfer-alt', class: 'bx-transfer-alt' },
  { name: 'trash', class: 'bx-trash' },
  { name: 'trash-alt', class: 'bx-trash-alt' },
  { name: 'trending-down', class: 'bx-trending-down' },
  { name: 'trending-up', class: 'bx-trending-up' },
  { name: 'trophy', class: 'bx-trophy' },
  { name: 'truck', class: 'bx-truck' },
  { name: 'tv', class: 'bx-tv' },
  { name: 'underline', class: 'bx-underline' },
  { name: 'undo', class: 'bx-undo' },
  { name: 'unite', class: 'bx-unite' },
  { name: 'unlink', class: 'bx-unlink' },
  { name: 'up-arrow', class: 'bx-up-arrow' },
  { name: 'up-arrow-alt', class: 'bx-up-arrow-alt' },
  { name: 'up-arrow-circle', class: 'bx-up-arrow-circle' },
  { name: 'upload', class: 'bx-upload' },
  { name: 'upside-down', class: 'bx-upside-down' },
  { name: 'upvote', class: 'bx-upvote' },
  { name: 'user', class: 'bx-user' },
  { name: 'user-check', class: 'bx-user-check' },
  { name: 'user-circle', class: 'bx-user-circle' },
  { name: 'user-minus', class: 'bx-user-minus' },
  { name: 'user-plus', class: 'bx-user-plus' },
  { name: 'user-pin', class: 'bx-user-pin' },
  { name: 'user-voice', class: 'bx-user-voice' },
  { name: 'user-x', class: 'bx-user-x' },
  { name: 'vector', class: 'bx-vector' },
  { name: 'vertical-center', class: 'bx-vertical-center' },
  { name: 'video', class: 'bx-video' },
  { name: 'video-off', class: 'bx-video-off' },
  { name: 'video-plus', class: 'bx-video-plus' },
  { name: 'video-recording', class: 'bx-video-recording' },
  { name: 'voicemail', class: 'bx-voicemail' },
  { name: 'volume', class: 'bx-volume' },
  { name: 'volume-full', class: 'bx-volume-full' },
  { name: 'volume-low', class: 'bx-volume-low' },
  { name: 'volume-mute', class: 'bx-volume-mute' },
  { name: 'walk', class: 'bx-walk' },
  { name: 'wallet', class: 'bx-wallet' },
  { name: 'wallet-alt', class: 'bx-wallet-alt' },
  { name: 'water', class: 'bx-water' },
  { name: 'webcam', class: 'bx-webcam' },
  { name: 'wifi', class: 'bx-wifi' },
  { name: 'wifi-off', class: 'bx-wifi-off' },
  { name: 'wind', class: 'bx-wind' },
  { name: 'window', class: 'bx-window' },
  { name: 'window-alt', class: 'bx-window-alt' },
  { name: 'window-close', class: 'bx-window-close' },
  { name: 'window-open', class: 'bx-window-open' },
  { name: 'windows', class: 'bx-windows' },
  { name: 'wine', class: 'bx-wine' },
  { name: 'wink-smile', class: 'bx-wink-smile' },
  { name: 'wink-tongue', class: 'bx-wink-tongue' },
  { name: 'won', class: 'bx-won' },
  { name: 'world', class: 'bx-world' },
  { name: 'wrench', class: 'bx-wrench' },
  { name: 'x', class: 'bx-x' },
  { name: 'x-circle', class: 'bx-x-circle' },
  { name: 'yen', class: 'bx-yen' },
  { name: 'zoom-in', class: 'bx-zoom-in' },
  { name: 'zoom-out', class: 'bx-zoom-out' }
]

const searchQuery = ref('')
const copiedIcon = ref('')
const page = ref(1)
const itemsPerPage = 48

// Filter icons based on search
const filteredIcons = computed(() => {
  if (!searchQuery.value) return boxIcons
  return boxIcons.filter(icon => 
    icon.name.toLowerCase().includes(searchQuery.value.toLowerCase())
  )
})

// Paginated icons
const paginatedIcons = computed(() => {
  const start = (page.value - 1) * itemsPerPage
  const end = start + itemsPerPage
  return filteredIcons.value.slice(start, end)
})

// Total pages calculation
const totalPages = computed(() => {
  return Math.ceil(filteredIcons.value.length / itemsPerPage)
})

// Reset to page 1 when search changes
watchEffect(() => {
  if (searchQuery.value) {
    page.value = 1
  }
})

// Copy the icon class
const copyIcon = (iconName) => {
  const icon = boxIcons.find(i => i.name === iconName)
  const text = `<i class="bx ${icon.class}"></i>`
  navigator.clipboard.writeText(text)
  copiedIcon.value = iconName
  setTimeout(() => (copiedIcon.value = ''), 1500)
}
</script>

<style scoped>
@import url('https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css');
input:focus {
  outline: none;
  border-color: #4f46e5;
  box-shadow: 0 0 0 2px rgba(79, 70, 229, 0.3);
}

.bx {
  font-size: 1.5rem;
  color: currentColor;
}
</style>